from sqlalchemy import Column, DateTime, Text, Date, DECIMAL, CHAR, Integer, Time, Boolean, VARCHAR
from config.dbconnection import Base

class Inspecciones(Base):
    __tablename__ = 'INSPECCIONES'
    ID = Column(Integer, primary_key=True, autoincrement=True, nullable=False)
    UNIDAD = Column(CHAR(8), default="")
    PLACA = Column(CHAR(8), default="")
    PROPI_IDEN = Column(CHAR(12), default="")
    NOMPROPI = Column(CHAR(50), default="")
    CONDUCTOR = Column(CHAR(12), default="")
    CEDULA = Column(CHAR(12), default="")
    NOMCONDU = Column(CHAR(40), default="")
    TIPO_INSPEC = Column(CHAR(2), default="")
    KILOMETRAJ = Column(Integer, default=0)
    CAUSA = Column(Text, default="")
    DESCRIPCION = Column(Text, default="")
    OBSERVA = Column(Text, default="")
    FECHA = Column(Date, default=None)
    HORA = Column(Time, default=None)
    NRO_COTIZA = Column(CHAR(12), default="")
    VLR_COTIZA = Column(DECIMAL(12, 2), default=0)
    VLR_MANOBRA = Column(Integer, default=0)
    ALFOMBRA = Column(Boolean, default=False)
    ANTENA = Column(Boolean, default=False)
    CARATRADIO = Column(Boolean, default=False)
    COMBUSTIBLE = Column(Boolean, default=False)
    COPASRINES = Column(Boolean, default=False)
    EXTINGUIDOR = Column(Boolean, default=False)
    FORMACOLIS = Column(Boolean, default=False)
    GATO = Column(Boolean, default=False)
    GPS = Column(Boolean, default=False)
    LAMPARAS = Column(Boolean, default=False)
    LLANTAREPU = Column(Boolean, default=False)
    LUZDELANTE = Column(Boolean, default=False)
    LUZTRACERA = Column(Boolean, default=False)
    PAGOMUNICI = Column(Boolean, default=False)
    PANAPASS = Column(Boolean, default=False)
    PIPA = Column(Boolean, default=False)
    PLACAMUNIC = Column(Boolean, default=False)
    POLISEGURO = Column(Boolean, default=False)
    REGISVEHIC = Column(Boolean, default=False)
    RETROVISOR = Column(Boolean, default=False)
    REVISADO = Column(Boolean, default=False)
    TAPICERIA = Column(Boolean, default=False)
    TRIANGULO = Column(Boolean, default=False)
    VIDRIOS = Column(Boolean, default=False)
    FOTO01 = Column(VARCHAR(200), default="")
    FOTO02 = Column(VARCHAR(200), default="")
    FOTO03 = Column(VARCHAR(200), default="")
    FOTO04 = Column(VARCHAR(200), default="")
    FOTO05 = Column(VARCHAR(200), default="")
    FOTO06 = Column(VARCHAR(200), default="")
    FOTO07 = Column(VARCHAR(200), default="")
    FOTO08 = Column(VARCHAR(200), default="")
    FOTO09 = Column(VARCHAR(200), default="")
    FOTO10 = Column(VARCHAR(200), default="")
    FOTO11 = Column(VARCHAR(200), default="")
    FOTO12 = Column(VARCHAR(200), default="")
    FOTO13 = Column(VARCHAR(200), default="")
    FOTO14 = Column(VARCHAR(200), default="")
    FOTO15 = Column(VARCHAR(200), default="")
    FOTO16 = Column(VARCHAR(200), default="")
    USUARIO = Column(CHAR(10), default="")
    FEC_CREADO = Column(DateTime, default=None)