from sqlalchemy import Column, String, Integer, Numeric, Date, Text, DateTime, DECIMAL, CHAR, Boolean
from config.dbconnection import Base

class PermisosUsuario(Base):
  __tablename__ = 'PERMISOSUSUARIO'

  CODIGO = Column(CHAR(50), primary_key=True)
  NOMBRE = Column(CHAR(40))
  GRUPO = Column(CHAR(2))
  DIAS = Column(Integer)
  COMISION = Column(DECIMAL(5,2))
  ESTADO = Column(Integer)
  FEC_ESTADO = Column(Date)
  BAJA_CONDU = Column(Integer)
  CAJERO = Column(Integer)
  GRUPO_CAJE = Column(Integer)
  FOTO = Column(Text)
  FEC_ULTCLA = Column(DateTime)
  FEC_ULTING = Column(DateTime)
  COD1 = Column(CHAR(10))
  EMPRESAS = Column(CHAR(30))
  OPCION01 = Column(CHAR(1))
  OPCION02 = Column(CHAR(1))
  OPCION03 = Column(CHAR(1))
  OPCION04 = Column(CHAR(1))
  OPCION05 = Column(CHAR(1))
  OPCION06 = Column(CHAR(1))
  OPCION07 = Column(CHAR(1))
  OPCION08 = Column(CHAR(1))
  OPCION09 = Column(CHAR(1))
  OPCION10 = Column(CHAR(1))
  OPCION11 = Column(CHAR(1))
  OPCION12 = Column(CHAR(1))
  OPCION13 = Column(CHAR(1))
  OPCION14 = Column(CHAR(1))
  OPCION15 = Column(CHAR(1))
  OPCION16 = Column(CHAR(1))
  TAREA01 = Column(CHAR(1))
  TAREA02 = Column(CHAR(1))
  TAREA03 = Column(CHAR(1))
  TAREA04 = Column(CHAR(1))
  TAREA05 = Column(CHAR(1))
  TAREA06 = Column(CHAR(1))
  TAREA07 = Column(CHAR(1))
  TAREA08 = Column(CHAR(1))
  TAREA09 = Column(CHAR(1))
  TAREA10 = Column(CHAR(1))
  TAREA11 = Column(CHAR(1))
  TAREA12 = Column(CHAR(1))
  PASSSWORD = Column(CHAR(1))
  FEC_CREADO = Column(DateTime)
