from sqlalchemy import Column, String, DateTime, Text, Date, CHAR, DECIMAL
from config.dbconnection import Base

class Propietarios(Base):
    __tablename__ = 'PROPIETARIOS'
    CODIGO = Column(CHAR(12), primary_key=True, nullable=False)
    ABREVIADO = Column(CHAR(20))
    NOMBRE = Column(CHAR(50))
    NIT = Column(DECIMAL(10, 0))
    CONTROL = Column(CHAR(2))
    RUC = Column(CHAR(18))
    RAZONSOCIA = Column(CHAR(50))
    CIUDAD = Column(CHAR(5))
    DIRECCION = Column(CHAR(60))
    TELEFONO = Column(CHAR(30))
    CELULAR = Column(CHAR(30))
    FEC_NACIMI = Column(Date)
    FEC_INGRES = Column(Date)
    CELULAR1 = Column(CHAR(30))
    REPRESENTA = Column(CHAR(40))
    REP_SEXO = Column(CHAR(10))
    REP_ESTADO = Column(CHAR(20))
    REP_TIPDOC = Column(CHAR(12))
    REP_NUMERO = Column(CHAR(20))
    REP_NACION = Column(CHAR(10))
    FICHA = Column(CHAR(40))
    DOCUMENTO = Column(CHAR(40))
    CONTACTO = Column(CHAR(40))
    CORREO = Column(CHAR(12))
    CORREO1 = Column(CHAR(20))
    ESTADO = Column(DECIMAL(1, 0))
    FEC_ESTADO = Column(Date)
    USUARIO = Column(CHAR(10))
    CENTRAL = Column(CHAR(12))
    BANCO1 = Column(CHAR(20))
    TIPOCTA1 = Column(CHAR(20))
    CUENTA1 = Column(CHAR(15))
    BANCO2 = Column(CHAR(10))
    TIPOCTA2 = Column(CHAR(10))
    CUENTA2 = Column(CHAR(40))
    GRUPO = Column(CHAR(10))
    IMPUESTO = Column(DECIMAL(2, 0))
    DESCUENTO = Column(DECIMAL(5, 0))
    ADM_PARADO = Column(DECIMAL(3, 0))
    FEC_CREADO = Column(Date)
    USU_CREADO = Column(CHAR(12))
    USU_MODIFI = Column(CHAR(12))
    SEL = Column(CHAR(1))
