from sqlalchemy import Column, String, DateTime, Text, Date, CHAR, DECIMAL
from config.dbconnection import Base

class Propietarios(Base):
    __tablename__ = 'PROPIETARIOS'
    CODIGO = Column(CHAR(12), primary_key=True, nullable=False)
    ABREVIADO = Column(CHAR(20), default='')
    NOMBRE = Column(CHAR(50), default='')
    NIT = Column(DECIMAL(10, 0), default=0)
    CONTROL = Column(CHAR(2), default='')
    RUC = Column(CHAR(18), default='')
    RAZONSOCIA = Column(CHAR(50), default='')
    CIUDAD = Column(CHAR(5), default='')
    DIRECCION = Column(CHAR(60), default='')
    TELEFONO = Column(CHAR(30), default='')
    CELULAR = Column(CHAR(30), default='')
    FEC_NACIMI = Column(Date)
    FEC_INGRES = Column(Date)
    CELULAR1 = Column(CHAR(30), default='')
    REPRESENTA = Column(CHAR(40), default='')
    REP_SEXO = Column(CHAR(10), default='')
    REP_ESTADO = Column(CHAR(20), default='')
    REP_TIPDOC = Column(CHAR(12), default='')
    REP_NUMERO = Column(CHAR(20), default='')
    REP_NACION = Column(CHAR(10), default='')
    FICHA = Column(CHAR(40), default='')
    DOCUMENTO = Column(CHAR(40), default='')
    CONTACTO = Column(CHAR(40), default='')
    CORREO = Column(CHAR(12), default='')
    CORREO1 = Column(CHAR(20), default='')
    ESTADO = Column(DECIMAL(1, 0), default=0)
    FEC_ESTADO = Column(Date)
    USUARIO = Column(CHAR(10), default='')
    CENTRAL = Column(CHAR(12), default='')
    BANCO1 = Column(CHAR(20), default='')
    TIPOCTA1 = Column(CHAR(20), default='')
    CUENTA1 = Column(CHAR(15), default='')
    BANCO2 = Column(CHAR(10), default='')
    TIPOCTA2 = Column(CHAR(10), default='')
    CUENTA2 = Column(CHAR(40), default='')
    GRUPO = Column(CHAR(10), default='')
    IMPUESTO = Column(DECIMAL(2, 0), default=0)
    DESCUENTO = Column(DECIMAL(5, 0), default=0)
    ADM_PARADO = Column(DECIMAL(3, 0), default=0)
    FEC_CREADO = Column(Date)
    USU_CREADO = Column(CHAR(12), default='')
    USU_MODIFI = Column(CHAR(12), default='')
    SEL = Column(CHAR(1), default='')