from sqlalchemy import Column, CHAR, DECIMAL, Date, DateTime, TEXT, VARCHAR
from config.dbconnection import Base

class Vehiculos(Base):
    __tablename__ = 'VEHICULOS'

    PLACA = Column(CHAR(8), primary_key=True, default="")
    NUMERO = Column(CHAR(8), default="")
    CONSECUTIV = Column(CHAR(6), default="")
    MARCA = Column(CHAR(2), default="")
    NOMMARCA = Column(CHAR(30), default="")
    LINEA = Column(CHAR(25), default="")
    MODELO = Column(CHAR(4), default="")
    LICETRANSI = Column(CHAR(20), default="")
    CILINDRAJE = Column(CHAR(4), default="")
    COLORES = Column(CHAR(20), default="")
    SERVICIO = Column(CHAR(30), default="")
    CLASEVEHIC = Column(CHAR(30), default="")
    TIPOCARROC = Column(CHAR(30), default="")
    COMBUSTIBL = Column(CHAR(20), default="")
    CAPACIDAD = Column(CHAR(8), default="")
    MOTORNRO = Column(CHAR(20), default="")
    MOTORREG = Column(CHAR(3), default="")
    MOTORVIN = Column(CHAR(20), default="")
    SERIENRO = Column(CHAR(20), default="")
    SERIEREG = Column(CHAR(3), default="")
    CHASISNRO = Column(CHAR(20), default="")
    CHASISREG = Column(CHAR(3), default="")
    NRO_CUPO = Column(CHAR(12), default="")
    PERMISONRO = Column(CHAR(12), default="")
    PERMISOVCE = Column(Date, default=None)
    PROPI_IDEN = Column(CHAR(12), default="")
    CTA_GASTO = Column(CHAR(12), default="")
    CENTRAL = Column(CHAR(12), default="")
    PATIO = Column(CHAR(2), default="")
    FOTO = Column(TEXT, default="")
    FOTO01 = Column(TEXT, default="")
    FOTO02 = Column(TEXT, default="")
    FOTO03 = Column(TEXT, default="")
    FOTO04 = Column(TEXT, default="")
    FOTO05 = Column(TEXT, default="")
    FOTO06 = Column(TEXT, default="")
    FOTO07 = Column(TEXT, default="")
    FOTO08 = Column(TEXT, default="")
    FOTO09 = Column(TEXT, default="")
    FOTO10 = Column(TEXT, default="")
    FOTO11 = Column(TEXT, default="")
    FOTO12 = Column(TEXT, default="")
    FOTO13 = Column(TEXT, default="")
    FOTO14 = Column(TEXT, default="")
    FOTO15 = Column(TEXT, default="")
    FOTO16 = Column(TEXT, default="")
    DOCU00 = Column(TEXT, default="")
    DOCU01 = Column(TEXT, default="")
    DOCU02 = Column(TEXT, default="")
    DOCU03 = Column(TEXT, default="")
    DOCU04 = Column(TEXT, default="")
    DOCU05 = Column(TEXT, default="")
    DOCU06 = Column(TEXT, default="")
    DOCU07 = Column(TEXT, default="")
    DOCU08 = Column(TEXT, default="")
    DOCU09 = Column(TEXT, default="")
    DOCU10 = Column(TEXT, default="")
    DOCU11 = Column(TEXT, default="")
    DOCU12 = Column(TEXT, default="")
    INFO_PANAP = Column(CHAR(1), default="")
    PANAPASSNU = Column(CHAR(12), default="")
    PANAPASSPW = Column(CHAR(12), default="")
    SDO_PLACA = Column(CHAR(8), default="")
    SDO_PANAPA = Column(CHAR(8), default="")
    GPS = Column(CHAR(1), default="")
    GPS_NRO = Column(CHAR(15), default="")
    GPS_FEC = Column(DateTime, default=None)
    OBSERVA = Column(TEXT, default="")
    RESTR_MOBI = Column(TEXT, default="")
    BLINDAJE = Column(VARCHAR(15), default="")
    POTENCIAHP = Column(CHAR(6), default="")
    DECLA_IMPO = Column(CHAR(20), default="")
    NE = Column(CHAR(3), default="")
    FEC_IMPORT = Column(DateTime, default=None)
    PUERTAS = Column(CHAR(1), default="")
    LIMI_PROPI = Column(CHAR(80), default="")
    FEC_MATRIC = Column(DateTime, default=None)
    FEC_EXPEDI = Column(DateTime, default=None)
    FEC_VENCIM = Column(DateTime, default=None)
    ORG_TRANSI = Column(CHAR(50), default="")
    COD_BARRAS = Column(CHAR(18), default="")
    LATERAL = Column(CHAR(8), default="")
    KILO_ANTES = Column(DECIMAL(8, 2), default=0)
    KILOMETRAJ = Column(DECIMAL(8, 2), default=0)
    MODALIDAD = Column(CHAR(2), default="")
    DOC_SOAT = Column(CHAR(20), default="")
    FEC_SOAT = Column(DateTime, default=None)
    DOC_AMBIEN = Column(CHAR(20), default="")
    FEC_AMBIEN = Column(DateTime, default=None)
    DOC_SEGCON = Column(CHAR(20), default="")
    FEC_SEGCON = Column(DateTime, default=None)
    DOC_TAROPE = Column(CHAR(20), default="")
    FEC_TAROPE = Column(DateTime, default=None)
    DOC_RESCIV = Column(CHAR(20), default="")
    FEC_RESCIV = Column(DateTime, default=None)
    DOC_RESCI2 = Column(CHAR(20), default="")
    FEC_RESCI2 = Column(DateTime, default=None)
    DOC_EXTING = Column(CHAR(20), default="")
    FEC_EXTING = Column(DateTime, default=None)
    DOC_TECNOM = Column(CHAR(20), default="")
    FEC_TECNOM = Column(DateTime, default=None)
    DOC_PLAPAR = Column(CHAR(20), default="")
    FEC_PLAPAR = Column(Date, default=None)
    DOC_PLAPUB = Column(CHAR(20), default="")
    FEC_PLAPUB = Column(Date, default=None)
    DOC_CEROPE = Column(CHAR(20), default="")
    FEC_CEROPE = Column(DateTime, default=None)
    FORMAPAGO = Column(CHAR(20), default="")
    PAGO_LUN = Column(CHAR(1), default="")
    PAGO_MAR = Column(CHAR(1), default="")
    PAGO_MIE = Column(CHAR(1), default="")
    PAGO_JUE = Column(CHAR(1), default="")
    PAGO_VIE = Column(CHAR(1), default="")
    PAGO_SAB = Column(CHAR(1), default="")
    PAGO_DOM = Column(CHAR(1), default="")
    FEC_1PAGO = Column(DateTime, default=None)
    FEC_ULTPAG = Column(DateTime, default=None)
    VLR_ULTPAG = Column(DECIMAL(12, 2), default=0)
    REC_ULTPAG = Column(DECIMAL(12, 2), default=0)
    MULTA = Column(DECIMAL(12, 2), default=0)
    FEC_1MANTE = Column(DateTime, default=None)
    FEC_ULTMAN = Column(DateTime, default=None)
    CATEGORIA = Column(CHAR(20), default="")
    EST_LLAVES = Column(CHAR(1), default="")
    tipo_llave = Column(CHAR(1), default="")
    FUN_LLAVES = Column(CHAR(12), default="")
    NRO_LLAVES = Column(CHAR(4), default="")
    MSG_LLAVES = Column(TEXT, default="")
    NROENTREGA = Column(CHAR(12), default="")
    CUO_DIARIA = Column(DECIMAL(8, 2), default=0)
    CTA_RENTA = Column(DECIMAL(8, 2), default=0)
    NUEVOUSADO = Column(CHAR(1), default="")
    CTA_SINIES = Column(DECIMAL(8, 2), default=0)
    VLR_DEPOSI = Column(DECIMAL(8, 2), default=0)
    CON_CUPO = Column(CHAR(1), default="1")
    PAGA_ADMON = Column(CHAR(1), default="")
    GLOBAL_UND = Column(CHAR(1), default="")
    CUO_ADMON = Column(DECIMAL(10, 2), default=0)
    CUO_REPVEH = Column(DECIMAL(10, 2), default=0)
    CUO_MANTEN = Column(DECIMAL(10, 2), default=0)
    CUO_RENDIM = Column(DECIMAL(10, 2), default=0)
    ESTATUS = Column(DECIMAL(1, 0), default=0)
    GRUPODIARI = Column(CHAR(2), default="")
    PREND_APAG = Column(CHAR(1), default="")
    PIQUERA = Column(CHAR(2), default="")
    NOMPIQUERA = Column(VARCHAR(60), default="")
    FEC_PIQUER = Column(DateTime, default=None)
    TURNO = Column(CHAR(2), default="")
    ESTADO = Column(CHAR(2), default="")
    ABREVIADO = Column(CHAR(8), default="")
    NOMESTADO = Column(CHAR(30), default="")
    FEC_ESTADO = Column(Date, default=None)
    ESTA_SINIE = Column(CHAR(1), default="")
    FEC_SINIES = Column(Date, default=None)
    CONDUCTOR = Column(CHAR(12), default="")
    CUO_DIA = Column(DECIMAL(8, 2), default=0)
    TURNO2 = Column(CHAR(2), default="")
    ESTADO2 = Column(CHAR(2), default="")
    FEC_ESTAD2 = Column(Date, default=None)
    CONDUCTOR2 = Column(CHAR(12), default="")
    CUO_DIA2 = Column(DECIMAL(8, 2), default=0)
    TURNO3 = Column(CHAR(2), default="")
    ESTADO3 = Column(CHAR(2), default="")
    FEC_ESTAD3 = Column(Date, default=None)
    CONDUCTOR3 = Column(CHAR(12), default="")
    CUO_DIA3 = Column(DECIMAL(8, 2), default=0)
    TURNO4 = Column(CHAR(2), default="")
    ESTADO4 = Column(CHAR(2), default="")
    FEC_ESTAD4 = Column(Date, default=None)
    CONDUCTOR4 = Column(CHAR(12), default="")
    CUO_DIA4 = Column(DECIMAL(8, 2), default=0)
    FAC_COMPRA = Column(DECIMAL(10, 2), default=0)
    FEC_COMPRA = Column(Date, default=None)
    VLR_COMPRA = Column(DECIMAL(12, 2), default=0)
    VALOR = Column(DECIMAL(12, 2), default=0)
    POLIZA = Column(CHAR(20), default="")
    FEC_POLIZA = Column(Date, default=None)
    LUN = Column(CHAR(1), default="")
    MAR = Column(CHAR(1), default="")
    MIE = Column(CHAR(1), default="")
    JUE = Column(CHAR(1), default="")
    VIE = Column(CHAR(1), default="")
    SAB = Column(CHAR(1), default="")
    DOM = Column(CHAR(1), default="")
    INGRESOS = Column(DECIMAL(12, 2), default=0)
    GASTOS = Column(DECIMAL(12, 2), default=0)
    NETO = Column(DECIMAL(12, 2), default=0)
    FEC_CREADO = Column(DateTime, default=None)
    NOMPATIO = Column(CHAR(40), default="")
    DETALPATIO = Column(VARCHAR(60), default="")
    NOMCENTRAL = Column(VARCHAR(50), default="")
    EMPRESA = Column(VARCHAR(50), default="")
    SEL = Column(CHAR(1), default="")
    FEC_CONTRA = Column(DateTime, default=None)